default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: mejuri
  password: mejuri
  database: mejuri_development

development:
  <<: *default

test:
  <<: *default
  database: mejuri_test

production:
  <<: *default
  database: mejuri_production
